-- Expanded culinary technique and skill catalogue
insert into techniques (key, label, category, description, prerequisites) values
  ('knife_grip_stance','Grip, Stance, and Knife Safety','Knife Skills','Holding the knife and food safely, standing stable at the board, and moving with control before speed.','{}'),
  ('knife_maintenance','Honing and Sharpening','Knife Skills','Keeping knives safe and effective by honing edges regularly and sharpening when the edge is actually dull.','{"knife_grip_stance"}'),
  ('dice','Dicing','Knife Skills','Cutting food into uniform cubes so pieces cook evenly and present cleanly.','{"knife_grip_stance"}'),
  ('julienne','Julienne','Knife Skills','Cutting food into thin matchstick strips, usually about 1/8 inch by 1/8 inch by 2 inches.','{"knife_grip_stance"}'),
  ('brunoise','Brunoise','Knife Skills','Cutting very small uniform cubes, usually made by dicing julienne strips.','{"julienne","dice"}'),
  ('batonnet','Batonnet','Knife Skills','Cutting food into thicker sticks, usually about 1/4 inch by 1/4 inch by 2 inches.','{"knife_grip_stance"}'),
  ('macedoine','Macédoine','Knife Skills','Cutting medium uniform cubes, commonly about 1/4 inch, often from batonnet pieces.','{"batonnet","dice"}'),
  ('paysanne','Paysanne','Knife Skills','Cutting thin, flat pieces that follow the ingredient shape for quick, even cooking.','{"knife_grip_stance"}'),
  ('chiffonade','Chiffonade','Knife Skills','Stacking leafy greens or herbs, rolling them, and slicing into thin ribbons.','{"knife_grip_stance"}'),
  ('mince','Mincing','Knife Skills','Chopping food into very small pieces to distribute strong flavors evenly.','{"dice"}'),
  ('rondelle','Rondelle','Knife Skills','Cutting cylindrical vegetables into round coins of even thickness.','{"knife_grip_stance"}'),
  ('tourne','Tourné','Knife Skills','Trimming vegetables into a seven-sided oval barrel shape for classic presentation and even cooking.','{"knife_grip_stance"}'),
  ('saute','Sautéing','Dry-Heat Cooking Methods','Cooking food quickly in a small amount of fat over medium-high to high heat while keeping it moving.','{}'),
  ('pan_fry','Pan-Frying','Dry-Heat Cooking Methods','Cooking food in a moderate layer of fat so the surface browns while the inside cooks through.','{"saute"}'),
  ('sear','Searing','Dry-Heat Cooking Methods','Using high heat to build a browned, flavorful crust through surface browning before finishing as needed.','{}'),
  ('pan_roast','Pan-Roasting','Dry-Heat Cooking Methods','Starting food in a hot pan for browning, then finishing in the oven for even cooking.','{"sear","roast"}'),
  ('roast','Roasting','Dry-Heat Cooking Methods','Cooking food uncovered in an oven with dry heat, usually for browning and concentrated flavor.','{}'),
  ('bake','Baking','Dry-Heat Cooking Methods','Cooking with dry oven heat, especially for breads, pastries, casseroles, and delicate structured foods.','{}'),
  ('grill','Grilling','Dry-Heat Cooking Methods','Cooking food on a grate over direct heat for char, smoke, and fast surface browning.','{}'),
  ('broil','Broiling','Dry-Heat Cooking Methods','Cooking food under intense overhead heat to brown, char, or finish quickly.','{"grill"}'),
  ('fry','Frying','Dry-Heat Cooking Methods','Cooking food in hot fat, including shallow-frying and deep-frying.','{}'),
  ('deep_fry','Deep-Frying','Dry-Heat Cooking Methods','Submerging food in hot oil to create rapid browning and a crisp exterior.','{"fry"}'),
  ('shallow_fry','Shallow-Frying','Dry-Heat Cooking Methods','Cooking food partly submerged in hot fat, turning as needed for even browning.','{"fry"}'),
  ('hot_smoke','Hot Smoking','Dry-Heat Cooking Methods','Cooking and flavoring food with smoke at temperatures high enough to cook it through.','{}'),
  ('cold_smoke','Cold Smoking','Dry-Heat Cooking Methods','Flavoring food with cool smoke without fully cooking it, usually after curing or with strict food-safety control.','{"cure"}'),
  ('boil','Boiling','Moist-Heat Cooking Methods','Cooking food in a full rolling boil, useful for pasta, hardy vegetables, and some blanching.','{}'),
  ('simmer','Simmering','Moist-Heat Cooking Methods','Cooking liquid just below boiling so small bubbles break gently at the surface.','{}'),
  ('poach','Poaching','Moist-Heat Cooking Methods','Cooking delicate food gently in liquid below a simmer, either shallow or deep.','{"simmer"}'),
  ('shallow_poach','Shallow Poaching','Moist-Heat Cooking Methods','Gently cooking delicate food in a small amount of liquid, often covered with parchment.','{"poach"}'),
  ('deep_poach','Deep Poaching','Moist-Heat Cooking Methods','Fully submerging delicate food in gentle hot liquid for even, controlled cooking.','{"poach"}'),
  ('blanch','Blanching and Shocking','Moist-Heat Cooking Methods','Briefly boiling food, then chilling it rapidly in ice water to stop cooking and set color or texture.','{"boil"}'),
  ('steam','Steaming','Moist-Heat Cooking Methods','Cooking food with steam over boiling water for gentle heat and minimal dilution of flavor.','{}'),
  ('braise','Braising','Moist-Heat Cooking Methods','A combination method: searing food in fat, then slow-cooking it covered with a small amount of liquid.','{"sear","simmer"}'),
  ('stew','Stewing','Moist-Heat Cooking Methods','A combination method: cooking smaller pieces fully submerged in liquid over low heat until tender.','{"simmer"}'),
  ('maillard','Maillard Reaction','Food Science & Chemistry','Browning proteins and reducing sugars with heat to build savory, complex flavor.','{"sear"}'),
  ('caramelization','Caramelization','Food Science & Chemistry','Browning sugars specifically, creating nutty, bitter, and sweet complexity distinct from Maillard browning.','{}'),
  ('emulsify','Emulsification','Food Science & Chemistry','Combining liquids that normally separate into a stable sauce or dressing, such as mayonnaise, hollandaise, or vinaigrette.','{}'),
  ('gelatinize','Gelatinization and Starch Thickening','Food Science & Chemistry','Using heat and liquid to swell starch granules for thickening through roux, slurries, or starches.','{}'),
  ('protein_coagulation','Protein Denaturation and Coagulation','Food Science & Chemistry','Changing protein structure with heat, acid, salt, or agitation so food sets, firms, or curdles.','{}'),
  ('ferment','Fermentation','Food Science & Chemistry','Using microorganisms to transform food, as in bread, pickles, kimchi, miso, yogurt, and other ferments.','{}'),
  ('osmosis_brining_curing','Osmosis, Brining, and Curing','Food Science & Chemistry','Using salt, sugar, and concentration gradients to season, preserve, and change texture.','{}'),
  ('cure','Curing','Food Science & Chemistry','Preserving and seasoning food with salt, sugar, smoke, or nitrites while managing time and temperature carefully.','{"osmosis_brining_curing"}'),
  ('pickle','Pickling','Food Science & Chemistry','Preserving and flavoring food in acid or through lacto-fermentation.','{"ferment"}'),
  ('ph','Acids, Bases, and pH','Food Science & Chemistry','Using acidity and alkalinity to control flavor, texture, browning, leavening, preservation, and color.','{}'),
  ('mother_sauces','Five Mother Sauces','Stocks, Sauces & Soups','Understanding béchamel, velouté, espagnole, tomato, and hollandaise as foundations for classic sauces.','{}'),
  ('stock_white','White Stock','Stocks, Sauces & Soups','Making a light stock from bones or vegetables without roasting, used for delicate soups and sauces.','{}'),
  ('stock_brown','Brown Stock','Stocks, Sauces & Soups','Roasting bones and aromatics before simmering to build a darker, richer stock.','{"roast","maillard"}'),
  ('fumet','Fumet','Stocks, Sauces & Soups','Making a quick, delicate fish stock with bones, aromatics, and gentle simmering.','{"fish_cleaning"}'),
  ('court_bouillon','Court Bouillon','Stocks, Sauces & Soups','Making a short-cooked aromatic poaching liquid, often for fish or vegetables.','{"poach"}'),
  ('reduce','Reductions','Stocks, Sauces & Soups','Simmering liquid to evaporate water and concentrate flavor, body, and seasoning.','{"simmer"}'),
  ('glace_de_viande','Glaces and Glace de Viande','Stocks, Sauces & Soups','Reducing stock to a concentrated glaze used to enrich sauces and finished dishes.','{"stock_brown","reduce"}'),
  ('deglaze','Deglazing and Pan Sauces','Stocks, Sauces & Soups','Adding liquid to a hot pan to dissolve browned bits and build a quick sauce.','{"sear","reduce"}'),
  ('roux','Roux','Stocks, Sauces & Soups','Cooking flour and fat together as a white, blond, or brown thickener for sauces and soups.','{"gelatinize"}'),
  ('liaison','Liaison','Stocks, Sauces & Soups','Enriching and lightly thickening a sauce or soup with egg yolks and cream without scrambling it.','{"temper","protein_coagulation"}'),
  ('beurre_manie','Beurre Manié','Stocks, Sauces & Soups','Kneading butter and flour together, then whisking it into liquid as a last-minute thickener.','{"gelatinize"}'),
  ('consomme','Consommé Clarification','Stocks, Sauces & Soups','Clarifying stock with a protein raft to produce a clear, intensely flavored broth.','{"stock_white","protein_coagulation"}'),
  ('bisque','Bisques','Stocks, Sauces & Soups','Making rich, smooth shellfish or vegetable soups with layered aromatics, stock, and finishing cream.','{"stock_white","puree_soup"}'),
  ('chowder','Chowders','Stocks, Sauces & Soups','Making hearty soups, often with seafood, potatoes, dairy, and a thick, rustic texture.','{"simmer"}'),
  ('puree_soup','Purée Soups','Stocks, Sauces & Soups','Cooking ingredients until tender, blending them smooth, and adjusting consistency and seasoning.','{"simmer"}'),
  ('temper','Tempering','Stocks, Sauces & Soups','Gradually raising the temperature of eggs, dairy, or chocolate to prevent curdling, scrambling, or seizing.','{}'),
  ('beurre_blanc','Beurre Blanc','Stocks, Sauces & Soups','Whisking cold butter into a wine-vinegar reduction to make a glossy butter sauce.','{"reduce","emulsify"}'),
  ('sous_vide','Sous Vide','Modern & Precision Techniques','Vacuum-sealing food and cooking it in a precisely temperature-controlled water bath.','{}'),
  ('spherification','Spherification','Modern & Precision Techniques','Using sodium alginate and calcium to create liquid-filled spheres in molecular cooking.','{"hydrocolloids"}'),
  ('gelification','Gelification','Modern & Precision Techniques','Setting liquids into gels with gelatin, agar, pectin, or other gelling agents.','{"hydrocolloids"}'),
  ('foams','Foams','Modern & Precision Techniques','Trapping gas in liquids or purées to create light, aromatic textures.','{"emulsify"}'),
  ('hydrocolloids','Hydrocolloids','Modern & Precision Techniques','Using agar, xanthan gum, sodium alginate, and related ingredients to thicken, gel, stabilize, or suspend.','{}'),
  ('dehydration','Dehydration and Powders','Modern & Precision Techniques','Removing moisture to concentrate flavor, create powders, and change texture.','{}'),
  ('flavor_extraction','Flavor Extraction','Modern & Precision Techniques','Pulling flavor into fats, alcohol, water, or syrups through infusion, pressure, heat, or time.','{"infusions"}'),
  ('anti_griddle','Anti-Griddle','Modern & Precision Techniques','Freezing or semi-freezing foods rapidly on an ultra-cold surface for modern texture work.','{}'),
  ('liquid_nitrogen','Liquid Nitrogen','Modern & Precision Techniques','Using extremely cold nitrogen for rapid freezing, shattering textures, and dramatic tableside effects with strict safety controls.','{}'),
  ('fold','Folding','Baking & Pastry','Gently combining a light airy mixture into a heavier one with a spatula to preserve volume.','{}'),
  ('cream','Creaming','Baking & Pastry','Beating butter and sugar until light and fluffy to incorporate air for structure and lift.','{}'),
  ('knead','Kneading','Baking & Pastry','Working dough by pressing and folding to develop gluten structure.','{}'),
  ('proof','Bread and Yeast Fermentation','Baking & Pastry','Letting yeast dough rise to develop flavor, gas, and structure before baking.','{"knead"}'),
  ('sourdough','Sourdough Starters','Baking & Pastry','Maintaining and using wild yeast and lactic bacteria cultures for bread flavor and leavening.','{"ferment","proof"}'),
  ('pate_brisee','Pâte Brisée','Baking & Pastry','Making a flaky, unsweetened shortcrust pastry for pies, tarts, and savory pastry.','{"fold"}'),
  ('pate_sucree','Pâte Sucrée','Baking & Pastry','Making a sweet, tender tart dough with enough structure for clean pastry shells.','{"cream"}'),
  ('laminate','Puff Pastry and Lamination','Baking & Pastry','Folding butter into dough repeatedly to create many flaky layers.','{"fold","knead"}'),
  ('pate_a_choux','Pâte à Choux','Baking & Pastry','Cooking flour paste, then beating in eggs to make steam-leavened pastry such as éclairs and profiteroles.','{"protein_coagulation"}'),
  ('custards_creams','Custards and Creams','Baking & Pastry','Controlling egg and dairy coagulation for pastry cream, crème anglaise, baked custards, and similar bases.','{"temper","protein_coagulation"}'),
  ('mousse','Mousses','Baking & Pastry','Lightening custard, chocolate, or fruit bases with whipped cream, meringue, or gelatin.','{"fold","custards_creams"}'),
  ('chocolate_tempering','Tempering Chocolate','Baking & Pastry','Controlling cocoa butter crystallization so chocolate sets glossy, snappy, and stable.','{"temper"}'),
  ('sugar_work','Sugar Work and Confectionery','Baking & Pastry','Cooking sugar to precise stages for caramel, candies, decorations, and confections.','{"caramelization"}'),
  ('meringue_french','French Meringue','Baking & Pastry','Whipping sugar into raw egg whites for a simple, light meringue.','{"protein_coagulation"}'),
  ('meringue_italian','Italian Meringue','Baking & Pastry','Streaming hot sugar syrup into whipped egg whites for a stable cooked meringue.','{"meringue_french","sugar_work"}'),
  ('meringue_swiss','Swiss Meringue','Baking & Pastry','Heating egg whites and sugar over a bain-marie before whipping for a dense, stable meringue.','{"meringue_french","temper"}'),
  ('fish_cleaning','Fish and Shellfish Cleaning','Butchery & Fabrication','Cleaning, scaling, trimming, and portioning fish and shellfish safely and neatly.','{}'),
  ('fillet_fish','Filleting Fish','Butchery & Fabrication','Removing fish fillets cleanly from the frame while minimizing waste and checking pin bones.','{"fish_cleaning"}'),
  ('poultry_breakdown','Breaking Down Poultry','Butchery & Fabrication','Separating a whole bird into usable parts such as breasts, thighs, drumsticks, wings, and carcass.','{}'),
  ('debone','Deboning','Butchery & Fabrication','Removing bones from meat, poultry, or fish while preserving usable flesh and shape.','{"poultry_breakdown"}'),
  ('poultry_trussing','Poultry Trussing','Butchery & Fabrication','Tying poultry to promote even cooking and compact presentation.','{"poultry_breakdown"}'),
  ('primal_beef','Beef Primal Cuts','Butchery & Fabrication','Understanding and breaking down major beef primals into subprimals and portions.','{}'),
  ('primal_pork','Pork Primal Cuts','Butchery & Fabrication','Understanding and breaking down major pork primals into subprimals and portions.','{}'),
  ('primal_lamb','Lamb Primal Cuts','Butchery & Fabrication','Understanding and breaking down major lamb primals into subprimals and portions.','{}'),
  ('sausage_making','Sausage-Making','Butchery & Fabrication','Grinding, seasoning, binding, stuffing, and safely cooking or curing sausage.','{"cure"}'),
  ('terrines_pates','Terrines and Pâtés','Butchery & Fabrication','Building seasoned forcemeats or pâtés, cooking them gently, and setting clean slices.','{"protein_coagulation","sausage_making"}'),
  ('seasoning_stages','Salting and Seasoning at the Right Stages','Seasoning & Flavor Building','Seasoning before, during, and after cooking to build flavor throughout the food instead of only on the surface.','{}'),
  ('mirepoix','Mirepoix','Seasoning & Flavor Building','Building a French aromatic base from onion, carrot, and celery.','{"dice"}'),
  ('sofrito','Sofrito','Seasoning & Flavor Building','Building a slow-cooked aromatic base used across Spanish, Italian, Latin American, and Caribbean cooking.','{"dice"}'),
  ('holy_trinity','Holy Trinity','Seasoning & Flavor Building','Building a Cajun and Creole aromatic base from onion, celery, and bell pepper.','{"dice"}'),
  ('herbs_spices','Herbs and Spices','Seasoning & Flavor Building','Using fresh herbs, dried herbs, whole spices, ground spices, blooming, toasting, and timing to control flavor.','{}'),
  ('sachet_bouquet_garni','Sachets and Bouquet Garni','Seasoning & Flavor Building','Bundling or containing herbs and aromatics so they season a dish and can be removed cleanly.','{"herbs_spices"}'),
  ('balance_salt_fat_acid_heat','Balancing Salt, Fat, Acid, and Heat','Seasoning & Flavor Building','Adjusting seasoning, richness, brightness, and spice so food tastes complete.','{"seasoning_stages"}'),
  ('marinades','Marinades','Seasoning & Flavor Building','Using seasoned liquids with salt, acid, enzymes, aromatics, or oil to flavor and sometimes tenderize food.','{"osmosis_brining_curing","ph"}'),
  ('rubs','Rubs','Seasoning & Flavor Building','Applying dry seasoning blends to build crust, aroma, and flavor before cooking.','{"seasoning_stages"}'),
  ('infusions','Infusions','Seasoning & Flavor Building','Steeping aromatics into oils, vinegars, alcohol, syrups, cream, or stock to transfer flavor.','{"herbs_spices"}'),
  ('mise_en_place','Mise en Place','Professional Kitchen Fundamentals','Organizing ingredients, tools, prep, and timing before cooking so execution is calm and controlled.','{}'),
  ('food_safety','Food Safety and Sanitation','Professional Kitchen Fundamentals','Managing hygiene, cross-contamination, HACCP thinking, and temperature danger zones.','{}'),
  ('brigade','Kitchen Brigade and Station Roles','Professional Kitchen Fundamentals','Understanding classic station roles and how professional kitchens divide responsibility during service.','{}'),
  ('plating','Plating and Presentation','Professional Kitchen Fundamentals','Arranging food with intention, contrast, restraint, garnish, and clean edges.','{}'),
  ('menu_development','Menu Development','Professional Kitchen Fundamentals','Designing menus around seasonality, balance, audience, operations, and repeatability.','{}'),
  ('costing_yield','Costing and Yield Management','Professional Kitchen Fundamentals','Calculating food cost, trim loss, portions, batch yields, and price implications.','{"menu_development"}'),
  ('service_timing','Time and Station Management','Professional Kitchen Fundamentals','Managing prep, pickups, sequencing, and pressure during service.','{"mise_en_place"}')
on conflict (key) do update set
  label = excluded.label,
  category = excluded.category,
  description = excluded.description,
  prerequisites = excluded.prerequisites;
